### ISSUE TITLE
Error `/assets/js/dist/*.min.js` not found

### ISSUE THREAD

**Issue by Rootjhon** [cotes2020/jekyll-theme-chirpy#1056]
**NOTE:** Before you start, the following should be completed.

- Read [Wiki][wiki] to understand the usage and the correct effect of functional design.
- Make sure no [similar issue(including closed ones)][issues] exists.
- Try to find the answer on [Jekyll Forum][forum] and [StackOverflow][stack_overflow].

[wiki]: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
[issues]: https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue
[forum]: https://talk.jekyllrb.com/
[stack_overflow]: https://stackoverflow.com/questions/tagged/jekyll

## Description

just run `bundle exec jekyll s` in localhost, 
```
F:\jekyll-theme-chirpy>bundle exec jekyll s
Configuration file: F:/jekyll-theme-chirpy/_config.yml
 Theme Config file: F:/jekyll-theme-chirpy/_config.yml
            Source: F:/jekyll-theme-chirpy
       Destination: F:/jekyll-theme-chirpy/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 9.802 seconds.
 Auto-regeneration: enabled for 'F:/jekyll-theme-chirpy'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

something error ...

```

[2023-05-22 16:06:19] ERROR `/assets/js/dist/home.min.js' not found.
[2023-05-22 16:06:20] ERROR `/assets/js/dist/post.min.js' not found.
[2023-05-22 16:06:24] ERROR `/assets/js/dist/home.min.js' not found.
[2023-05-22 16:06:26] ERROR `/assets/js/dist/post.min.js' not found.
[2023-05-22 16:06:28] ERROR `/assets/js/dist/home.min.js' not found.
[2023-05-22 16:06:32] ERROR `/assets/js/dist/post.min.js' not found.
[2023-05-22 16:06:33] ERROR `/assets/js/dist/home.min.js' not found.
[2023-05-22 16:07:14] ERROR `/assets/js/dist/post.min.js' not found.
[2023-05-22 16:07:17] ERROR `/assets/js/dist/home.min.js' not found.
```

**And** Github Action will failed 

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/12013966/b8b895ce-df9d-4b4b-8d72-9f64c5ca89ae)

**Comment by JinHanLei** [comment]
just run bash tools/init

**Comment by Blacknight318** [comment]
I renamed .github folder, commented out _check_status and _check_init and re-ran script, got same error when trying to run on fresh pull from release repo
```
> jekyll-theme-chirpy@6.0.1 prebuild
> npx rimraf assets/js/dist

/home/chief/chirpy-v6.0.1/jekyll-theme-chirpy/node_modules/minimatch/dist/cjs/ast.js:86
    #fillNegs() {
             ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/chief/chirpy-v6.0.1/jekyll-theme-chirpy/node_modules/minimatch/dist/cjs/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by Rootjhon** [comment]
> just run `bash tools/init`

It also happened in GitHub action.

**Comment by JinHanLei** [comment]
> I tried that solution as I was having the same issue, getting "Error: Commit unstaged files first, and then run this tool again." even when running bash tools/init --no-gh

try `git commit -m "xxx"`, commit files first and try again.

**Comment by lyducka** [comment]
I have the same question, I use GitHub action auto deploy to pages.

**Comment by lyducka** [comment]
I have solved this problem with the following solution.  
https://github.com/cotes2020/jekyll-theme-chirpy/issues/942#issuecomment-1479552757

**Comment by CoderSherlock** [comment]
> I renamed .github folder, commented out _check_status and _check_init and re-ran script, got same error when trying to run on fresh pull from release repo
> 
> ```
> > jekyll-theme-chirpy@6.0.1 prebuild
> > npx rimraf assets/js/dist
> 
> /home/chief/chirpy-v6.0.1/jekyll-theme-chirpy/node_modules/minimatch/dist/cjs/ast.js:86
>     #fillNegs() {
>              ^
> 
> SyntaxError: Unexpected token '('
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/home/chief/chirpy-v6.0.1/jekyll-theme-chirpy/node_modules/minimatch/dist/cjs/index.js:9:18)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> ```

+1 to this case. Any solutions?
