### ISSUE TITLE
Unable to stepup the theme on local system.

### ISSUE THREAD

**Issue by swastkk** [cotes2020/jekyll-theme-chirpy#1079]
After following the documentation, I am unable to use the command `bash tools/init`  in the https://chirpy.cotes.page/posts/getting-started/#option-1-using-the-chirpy-starter
Getting errors while running 
1. `bash tools/init`
```
➤ bash tools/init
bash: tools/init: No such file or directory
```
2. `bundle`
```
➤ bundle
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using bundler 2.4.12
Using rexml 3.2.5
Bundler::PermissionError: There was an error while trying to write to `/usr/lib/ruby/gems/3.0.0/cache`. It is likely that you
need to grant write permissions for that path.
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:440:in `fetch_gem'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:156:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing public_suffix (5.0.1), and Bundler cannot continue.

In Gemfile:
  html-proofer was resolved to 3.19.4, which depends on
    addressable was resolved to 2.8.4, which depends on
      public_suffix


Bundler::PermissionError: There was an error while trying to write to `/usr/lib/ruby/gems/3.0.0/cache`. It is likely that you
need to grant write permissions for that path.
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:440:in `fetch_gem'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:156:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing colorator (1.1.0), and Bundler cannot continue.

In Gemfile:
  jekyll-theme-chirpy was resolved to 6.0.1, which depends on
    jekyll-archives was resolved to 2.2.1, which depends on
      jekyll was resolved to 4.3.2, which depends on
        colorator


Bundler::PermissionError: There was an error while trying to write to `/usr/lib/ruby/gems/3.0.0/cache`. It is likely that you
need to grant write permissions for that path.
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:440:in `fetch_gem'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:156:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing concurrent-ruby (1.2.2), and Bundler cannot continue.

In Gemfile:
  jekyll-theme-chirpy was resolved to 6.0.1, which depends on
    jekyll-archives was resolved to 2.2.1, which depends on
      jekyll was resolved to 4.3.2, which depends on
        i18n was resolved to 1.14.1, which depends on
          concurrent-ruby


Bundler::PermissionError: There was an error while trying to write to `/usr/lib/ruby/gems/3.0.0/cache`. It is likely that you
need to grant write permissions for that path.
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:440:in `fetch_gem'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:156:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing http_parser.rb (0.8.0), and Bundler cannot continue.

In Gemfile:
  jekyll-theme-chirpy was resolved to 6.0.1, which depends on
    jekyll-archives was resolved to 2.2.1, which depends on
      jekyll was resolved to 4.3.2, which depends on
        em-websocket was resolved to 0.5.3, which depends on
          http_parser.rb


Bundler::PermissionError: There was an error while trying to write to `/usr/lib/ruby/gems/3.0.0/cache`. It is likely that you
need to grant write permissions for that path.
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:105:in `rescue in filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/shared_helpers.rb:102:in `filesystem_access'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:440:in `fetch_gem'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/lib/ruby/3.0.0/bundler/source/rubygems.rb:156:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/lib/ruby/3.0.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/lib/ruby/3.0.0/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:62:in `apply_func'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `loop'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:54:in `process_queue'
  /usr/lib/ruby/3.0.0/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing ffi (1.15.5), and Bundler cannot continue.

In Gemfile:
  html-proofer was resolved to 3.19.4, which depends on
    typhoeus was resolved to 1.4.0, which depends on
      ethon was resolved to 0.16.0, which depends on
        ffi
```
Please help me out...

**Comment by swastkk** [comment]
Solved this issue with changing the default location of the `$BUNDLE_PATH` to a writable location i.e 
```
export BUNDLE_PATH=~/.gems
```
 and after that running the command

 ```
bundle
```
or 
```
bundle install
```
