### ISSUE TITLE
MacOS: ModuleNotFoundError: No module named 'ruamel' when run bash run.sh

### ISSUE THREAD

**Issue by UniFreak** [cotes2020/jekyll-theme-chirpy#12]
Following your tutorial, but when in step of running `bash run.sh`, some error happened as below:

```sh
$ bash run.sh
Traceback (most recent call last):
  File "_scripts/py/init_all.py", line 10, in <module>
    import update_posts_lastmod
  File "/Users/fanghao/Projects/jekyll-theme-chirpy/.container/_scripts/py/update_posts_lastmod.py", line 26, in <module>
    from ruamel.yaml import YAML
ModuleNotFoundError: No module named 'ruamel'
```

Already runned `bundle install` successfully, thought I should run `gem install ruamel`, but this also error out:

```sh
$ gem install ruamel
ERROR:  Could not find a valid gem 'ruamel' (>= 0) in any repository
```

**Comment by UniFreak** [comment]
Solved, turns out `ruamel` is an python package named `ruamel_yaml`. Just ran `pip install ruamel_yaml` now all OK.
