### ISSUE TITLE
Dependency sass-embedded install failure

### ISSUE THREAD

**Issue by trstringer** [cotes2020/jekyll-theme-chirpy#1430]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

When I attempt to `bundle install` I get the following error:

```
Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to underlying error <bad response Forbidden 403
(https://rubygems.org/gems/sass-embedded-1.69.5-x86_64-linux.gem)>
```

### Steps To Reproduce

1. Clone the repo: `git clone git@github.com:cotes2020/jekyll-theme-chirpy.git jekyll-theme-chirpy-repro1`
2. `cd ./jekyll-theme-chirpy-repro1`
3. Set the bundle path (if I don't do this, I get permissions issues on `/usr/local/bin`, so doing this helps me get a path that non root has permissions on): `mkdir ~/bundlepath4 && bundle config path ~/bundlepath4`
4. `./tools/init`
5. `bundle install`

```
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching sass-embedded 1.69.5 (x86_64-linux)

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sass-embedded-1.69.5-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sass-embedded-1.69.5-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/sass-embedded-1.69.5-x86_64-linux.gem)

Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to underlying error <bad response Forbidden 403
(https://rubygems.org/gems/sass-embedded-1.69.5-x86_64-linux.gem)>
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/rubygems_integration.rb:497:in `rescue in download_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/rubygems_integration.rb:469:in `download_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:481:in `download_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:443:in `fetch_gem'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:427:in `fetch_gem_if_possible'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/source/rubygems.rb:161:in `install'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:62:in `apply_func'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in `loop'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:54:in `process_queue'
  /usr/share/rubygems-integration/all/gems/bundler-2.4.20/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing sass-embedded (1.69.5), and Bundler cannot continue.

In Gemfile:
  jekyll-theme-chirpy was resolved to 6.3.1, which depends on
    jekyll-archives was resolved to 2.2.1, which depends on
      jekyll was resolved to 4.3.2, which depends on
        jekyll-sass-converter was resolved to 3.0.0, which depends on
          sass-embedded
```

### Expected Behavior

`bundle install` successfully.

### Environment

- Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
- Jekyll: "bundler: command not found: jekyll Install missing gem executables with `bundle install`"
- Chirpy:

```
Could not find compatible versions

Because every version of jekyll-theme-chirpy depends on jekyll-include-cache ~> 0.2
  and jekyll-include-cache ~> 0.2 could not be found in locally installed gems,
  jekyll-theme-chirpy cannot be used.
So, because Gemfile depends on jekyll-theme-chirpy >= 0,
  version solving has failed.```
```

### Anything else?

The error does in fact show this URL: `https://rubygems.org/gems/sass-embedded-1.69.5-x86_64-linux.gem` which doesn't exist. It looks like there is a suffix that is missing there (e.g. `-gnu`) but I'm unsure how to proceed.

**Comment by ntkme** [comment]
See https://github.com/sass-contrib/sass-embedded-host-ruby/issues/176

**Comment by trstringer** [comment]
Thank you for the help!
