### ISSUE TITLE
Running tools/run.sh via Docker gives Permission denied @ dir_initialize - /srv/jekyll/.container (Errno::EACCES)

### ISSUE THREAD

**Issue by gdejong** [cotes2020/jekyll-theme-chirpy#145]
As suggested in https://github.com/cotes2020/jekyll-theme-chirpy/pull/121#issuecomment-687910956 I should be able to run Chirpy locally using Docker.

First step is to install the dependencies:
```
docker run --rm -it --volume="$PWD:/srv/jekyll" jekyll/jekyll bundle install
```

Now I should be able to run `bash tools/run.sh`:
```
$ docker run --rm -it \
> --volume="$PWD:/srv/jekyll" \
> --env JEKYLL_ENV=development \
> -p 4000:4000 jekyll/jekyll \
> bash tools/run.sh -H 0.0.0.0
$ bundle exec jekyll s -l -o -H 0.0.0.0
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 1.477 seconds.
                    ------------------------------------------------
      Jekyll 4.1.0   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
Traceback (most recent call last):
        47: from /usr/local/bin/bundle:23:in `<main>'
        46: from /usr/local/bin/bundle:23:in `load'
        45: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
        44: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
        43: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
        42: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
        41: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
        40: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
        39: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
        38: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        37: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        36: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
        35: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
        34: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
        33: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
        32: from /usr/gem/bin/jekyll:23:in `<top (required)>'
        31: from /usr/gem/bin/jekyll:23:in `load'
        30: from /usr/gem/gems/jekyll-4.1.0/exe/jekyll:15:in `<top (required)>'
        29: from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        28: from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        27: from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        26: from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        25: from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        24: from /usr/gem/gems/jekyll-4.1.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        23: from /usr/gem/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        22: from /usr/gem/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `each'
        21: from /usr/gem/gems/jekyll-4.1.0/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        20: from /usr/gem/gems/jekyll-4.1.0/lib/jekyll/commands/build.rb:43:in `process'
        19: from /usr/gem/gems/jekyll-4.1.0/lib/jekyll/commands/build.rb:88:in `watch'
        18: from /usr/gem/gems/jekyll-watch-2.2.1/lib/jekyll/watcher.rb:26:in `watch'
        17: from /usr/gem/gems/listen-3.2.1/lib/listen/listener.rb:91:in `start'
        16: from /usr/gem/gems/listen-3.2.1/lib/listen/fsm.rb:57:in `transition'
        15: from /usr/gem/gems/listen-3.2.1/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
        14: from /usr/gem/gems/listen-3.2.1/lib/listen/fsm.rb:121:in `call'
        13: from /usr/gem/gems/listen-3.2.1/lib/listen/fsm.rb:121:in `instance_eval'
        12: from /usr/gem/gems/listen-3.2.1/lib/listen/listener.rb:68:in `block in <class:Listener>'
        11: from /usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `start'
        10: from /usr/gem/gems/listen-3.2.1/lib/listen/adapter/base.rb:63:in `start'
         9: from /usr/gem/gems/listen-3.2.1/lib/listen/adapter/base.rb:40:in `configure'
         8: from /usr/gem/gems/listen-3.2.1/lib/listen/adapter/base.rb:40:in `each'
         7: from /usr/gem/gems/listen-3.2.1/lib/listen/adapter/base.rb:45:in `block in configure'
         6: from /usr/gem/gems/listen-3.2.1/lib/listen/adapter/linux.rb:32:in `_configure'
         5: from /usr/gem/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:202:in `watch'
         4: from /usr/gem/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:202:in `each'
         3: from /usr/gem/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:210:in `block in watch'
         2: from /usr/gem/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:200:in `watch'
         1: from /usr/gem/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:200:in `new'
/usr/gem/gems/rb-inotify-0.10.1/lib/rb-inotify/notifier.rb:200:in `initialize': Permission denied @ dir_initialize - /srv/jekyll/.container (Errno::EACCES)
```

Have you got any clues on what is causing this error?

**Comment by cotes2020** [comment]
> ```
> docker run --rm -it --volume="$PWD:/srv/jekyll" jekyll/jekyll bundle install
>```

No one told you to do this, because the Jekyll docker container will automatically run `bundle install`.

Now focus on the second issue:

> ```
> ... Permission denied @ dir_initialize - /srv/jekyll/.container (Errno::EACCES)
>```

If I am not wrong, you should have run `run.sh` or docker as `root` before. Go and checkout your files' onwership:

```
cd /path/to/chirpy-proj/
ls -lh
```

**Comment by gdejong** [comment]
So I made some progress, the `.container` directory kept being created owner by `root`. All other files and directories were owned by my regular user.

The `jekyll/jekyll` image runs as the `root` user.
```
$ docker run --rm -it jekyll/jekyll whoami
root
```

Within the container all files are owner by `jekyll`
```
$ docker run --rm -it --volume="$PWD:/srv/jekyll" jekyll/jekyll ls -lh
total 108K   
-rw-rw-r--    1 jekyll   jekyll       620 Oct  7 13:42 404.html
-rw-rw-r--    1 jekyll   jekyll       233 Oct  7 13:42 Gemfile
-rw-rw-r--    1 jekyll   jekyll      2.2K Oct  7 15:10 Gemfile.lock
<and many more>
```

I figured I could add a `chmod` to the `run.sh` script:
```
$ git diff tools/run.sh
index 938256e..e9f8d4c 100755
--- a/tools/run.sh
+++ b/tools/run.sh
@@ -53,6 +53,7 @@ _init() {
   cp -r "$WORK_DIR"/* "$temp"
   cp -r "${WORK_DIR}/.git" "$temp"
   mv "$temp" "${WORK_DIR}/${CONTAINER}"
+  chown -R jekyll:jekyll "${WORK_DIR}/${CONTAINER}"
 
   trap _cleanup INT
 }
```

Now I can run the `run.sh` script and I can access the site at http://0.0.0.0:4000

```
docker run --rm -it --volume="$PWD:/srv/jekyll" --env JEKYLL_ENV=development -p 4000:4000 jekyll/jekyll  bash tools/run.sh -H 0.0.0.0
```

I'll commit this in my repo. If you want and agree with this change I'd be happy to create a Pull Request. Just let me know.

Thanks for thinking along

**Comment by cotes2020** [comment]
Are you using the Docker Engine for Linux?

This is interesting because I use Docker for Mac and its container mount files using user `root` instead of user `jekyll`:

```
$ echo $OSTYPE
darwin19

$ docker run --rm -it --volume="$PWD:/srv/jekyll" jekyll/jekyll ls -lha
total 80K    
drwxr-xr-x   28 root     root         896 Oct  9 10:57 .
drwxr-xr-x    1 root     root        4.0K Sep  3 18:42 ..
-rw-r--r--    1 root     root        6.0K Jun  8 01:50 .DS_Store
-rw-r--r--    1 root     root          70 Sep  6 07:29 .env
drwxr-xr-x   17 root     root         544 Oct  9 10:46 .git
drwxr-xr-x    8 root     root         256 Sep 21 02:52 .github
-rw-r--r--    1 root     root         154 Sep 26 22:30 .gitignore
-rw-r--r--    1 root     root        1.5K Oct  8 03:50 .travis.yml
-rw-r--r--    1 root     root         620 Sep 29 14:11 404.html
-rw-r--r--    1 root     root         233 Oct  8 01:29 Gemfile
-rw-r--r--    1 root     root        1.1K Sep 16 10:01 LICENSE
-rw-r--r--    1 root     root        9.2K Oct  8 08:30 README.md
-rw-r--r--    1 root     root        5.1K Oct  8 08:24 _config.yml
drwxr-xr-x    8 root     root         256 Sep 29 14:11 _data
drwxr-xr-x   25 root     root         800 Sep 29 14:11 _includes
drwxr-xr-x    9 root     root         288 Oct  8 03:50 _layouts
drwxr-xr-x    6 root     root         192 Oct  8 08:30 _posts
drwxr-xr-x    3 root     root          96 Sep 16 10:01 _scripts
-rw-r--r--    1 root     root         267 Sep 16 10:01 app.js
drwxr-xr-x    5 root     root         160 Sep 16 10:01 assets
drwxr-xr-x    3 root     root          96 Oct  8 08:24 docs
-rw-r--r--    1 root     root        2.0K Sep 16 10:01 feed.xml
-rw-r--r--    1 root     root         166 Sep 16 10:01 index.html
-rw-r--r--    1 root     root         257 Sep 16 10:01 robots.txt
-rw-r--r--    1 root     root        2.3K Sep 16 10:01 sitemap.xml
-rw-r--r--    1 root     root        1.4K Sep 16 10:01 sw.js
drwxr-xr-x    6 root     root         192 Oct  8 03:26 tabs
drwxr-xr-x    8 root     root         256 Oct  9 10:34 tools
```

> According to the design of [`jekyll-docker`](https://github.com/envygeeks/jekyll-docker), it should be mount with user `jekyll`.

So I did not meet _Permission denied_ for the folder `.container` when running `jekyll-docker`. When I test it on the docker engine of linux, I can reproduce the issue you reported.

I have committed the solution you mentioned to the master branch, thanks for the report.

**Comment by gdejong** [comment]
Indeed I am using Docker on Linux (Ubuntu). I have just tested your changes and I can confirm they are working on Linux, thanks!

FYI I am actually using `docker-compose` to run the project.

`docker-compose.yml`:
```
version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    command: bash tools/run.sh --docker
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
```

This lets me run `docker-compose up` to start the project :)
