### ISSUE TITLE
Unable to build using docker. Jekyll::Converters::Scss encountered an error while converting

### ISSUE THREAD

**Issue by et-nik** [cotes2020/jekyll-theme-chirpy#1457]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Built from `jekyll-theme-chirpy`

### Describe the bug

I used [jekyll/builder](https://hub.docker.com/r/jekyll/builder/), [jekyll/jekyll](https://hub.docker.com/r/jekyll/jekyll/) docker images. Also I used alpine image with jekyll package with the same results.

I have an error:
```
Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    end of file reached
```

After some edition in `jekyll-theme-chirpy.scss` I can have an error:
```
Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    Broken pipe
```

### Steps To Reproduce

1. Clone the repo
```
git clone https://github.com/cotes2020/jekyll-theme-chirpy
```

2. Set privileges to avoid permission issues
```
chown -R 1000:1000 jekyll-theme-chirpy
```

3. Run build
```
docker run -it --rm -v $PWD/jekyll-theme-chirpy:/site -w /site jekyll/builder jekyll build
```

4. Error
```
Fetching gem metadata from https://rubygems.org/.........
Using bundler 2.3.25
Fetching public_suffix 5.0.4
Using colorator 1.1.0
Fetching concurrent-ruby 1.2.2
Installing public_suffix 5.0.4
Installing concurrent-ruby 1.2.2
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Fetching ffi 1.16.3
Using forwardable-extended 2.6.0
Fetching google-protobuf 3.25.1 (x86_64-linux)
Installing ffi 1.16.3 with native extensions
Installing google-protobuf 3.25.1 (x86_64-linux)
Using mercenary 0.4.0
Fetching racc 1.7.3
Installing racc 1.7.3 with native extensions
Fetching parallel 1.24.0
Installing parallel 1.24.0
Using rainbow 3.1.1
Using yell 2.2.2
Fetching zeitwerk 2.6.12
Installing zeitwerk 2.6.12
Using rb-fsevent 0.11.2
Fetching rexml 3.2.6
Installing rexml 3.2.6
Fetching liquid 4.0.4
Installing liquid 4.0.4
Fetching rouge 4.2.0
Installing rouge 4.2.0
Using safe_yaml 1.0.5
Fetching unicode-display_width 2.5.0
Installing unicode-display_width 2.5.0
Fetching webrick 1.8.1
Installing webrick 1.8.1
Using jekyll-paginate 1.1.0
Fetching addressable 2.8.6
Installing addressable 2.8.6
Using em-websocket 0.5.3
Fetching i18n 1.14.1
Installing i18n 1.14.1
Using pathutil 0.16.2
Fetching sass-embedded 1.69.5 (x86_64-linux-musl)
Installing sass-embedded 1.69.5 (x86_64-linux-musl)
Fetching nokogiri 1.16.0 (x86_64-linux)
Installing nokogiri 1.16.0 (x86_64-linux)
Using kramdown 2.4.0
Fetching terminal-table 3.0.2
Installing terminal-table 3.0.2
Fetching jekyll-sass-converter 3.0.0
Installing jekyll-sass-converter 3.0.0
Using kramdown-parser-gfm 1.1.0
Using ethon 0.16.0
Fetching typhoeus 1.4.1
Using rb-inotify 0.10.1
Fetching listen 3.8.0
Installing listen 3.8.0
Installing typhoeus 1.4.1
Using jekyll-watch 2.2.1
Fetching jekyll 4.3.3
Fetching html-proofer 4.4.3
Installing html-proofer 4.4.3
Installing jekyll 4.3.3
Fetching jekyll-archives 2.2.1
Fetching jekyll-include-cache 0.2.1
Installing jekyll-include-cache 0.2.1
Installing jekyll-archives 2.2.1
Using jekyll-redirect-from 0.16.0
Using jekyll-seo-tag 2.8.0
Using jekyll-sitemap 1.4.0
Using jekyll-theme-chirpy 6.3.1 from source at `.`
Bundle complete! 6 Gemfile dependencies, 46 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /site/_config.yml
 Theme Config file: /site/_config.yml
            Source: /site
       Destination: /site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    end of file reached
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `readbyte': end of file reached (EOFError)
	from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `block in read'
	from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `loop'
	from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `read'
	from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/connection.rb:29:in `block (2 levels) in initialize'
	from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/connection.rb:28:in `loop'
	from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/connection.rb:28:in `block in initialize'
```

## Broken pipe error
Sometimes I can have another error

```
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /site/ru/_config.yml
 Theme Config file: /site/ru/_config.yml
            Source: /site/ru
       Destination: /site/ru/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    Broken pipe
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/connection.rb:64:in `write': Broken pipe (Errno::EPIPE)
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/connection.rb:64:in `block in write'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/connection.rb:63:in `synchronize'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/connection.rb:63:in `write'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/dispatcher.rb:90:in `send_proto'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/dispatcher.rb:113:in `send_proto'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/host.rb:173:in `send_message'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/host.rb:44:in `block in compile_request'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/host.rb:137:in `block in await'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/host.rb:152:in `listen'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/host.rb:136:in `await'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded/host.rb:37:in `compile_request'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded.rb:212:in `compile_string'
        from /usr/gem/gems/sass-embedded-1.69.5/lib/sass/embedded.rb:50:in `compile_string'
        from /usr/gem/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/site.rb:211:in `render'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/gem/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/gem/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:27:in `load'
        from /usr/local/bundle/bin/jekyll:27:in `<main>'
```

### Expected Behavior

Expected success build

### Environment

- Ruby: ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
- Jekyll: jekyll 4.3.3
- Chirpy: 
```
* jekyll-theme-chirpy (6.3.1)
	Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
	Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
	Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
	Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
	Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
	Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
	Path: /site
```

**Comment by cotes2020** [comment]
Please don't just assert that you've found a bug, you should check out the `jekyll-docker` repository.

The `jekyll/jekyll` image has stopped updating for almost 2 years now, and the version of apline it relies on is too old.
