### ISSUE TITLE
which ruamel.yaml version ?

### ISSUE THREAD

**Issue by lucasbrasilino** [cotes2020/jekyll-theme-chirpy#15]
Which ruamel.yaml Chirpy depends on? ruamel.yaml has changed its API, and I'm trying to find a version that can be used. I'm using Python 3.5.2.
I've tried 0.16.5, 0.15.94, 0.14. Couldn't find the YAML class in them. 
```
$ bash tools/init.sh 
Traceback (most recent call last):
  File "_scripts/py/init_all.py", line 12, in <module>
    import update_posts_lastmod
  File "/home/lucas/jekyll-theme-chirpy/_scripts/py/update_posts_lastmod.py", line 28, in <module>
    from ruamel.yaml import YAML
ImportError: No module named ruamel.yaml
```

**Comment by cotes2020** [comment]
I'm using `0.16.5` (<https://pypi.org/project/ruamel.yaml/>), 

```
$ pip list | grep ruamel
ruamel.yaml      0.16.5 
ruamel.yaml.clib 0.1.2
```

**Comment by cotes2020** [comment]
```console
$ pip list | grep ruamel
ruamel.yaml      0.16.5 
ruamel.yaml.clib 0.1.2
```
