### ISSUE TITLE
Jekyll serve fails on GNU/Llinux

### ISSUE THREAD

**Issue by redacean** [cotes2020/jekyll-theme-chirpy#1708]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

I generated a jekyll site using the chirpy starter and simply cloned it locally. Without making any modifications to the content of the repo, Running `bundle exec jekyll s` after `bundle` gives the error below:

```
Configuration file: /home/kali/ctf-writeups/_config.yml
            Source: /home/kali/ctf-writeups
       Destination: /home/kali/ctf-writeups/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/connection.rb:54: warning: /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/ext/sass/dart-sass/src/dart: error while loading shared libraries: /lib/x86_64-linux-gnu/libc.so: invalid ELF header
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':                                 
                    Broken pipe
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/connection.rb:85:in `write': Broken pipe (Errno::EPIPE)
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/connection.rb:85:in `block in write'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/connection.rb:84:in `synchronize'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/connection.rb:84:in `write'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/dispatcher.rb:91:in `send_proto'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/channel.rb:59:in `send_proto'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/host.rb:220:in `send_message'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/host.rb:79:in `block in compile_request'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/host.rb:181:in `block in await'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/host.rb:199:in `listen'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/host.rb:180:in `await'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler/host.rb:78:in `compile_request'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/compiler.rb:171:in `compile_string'
        from /home/kali/gems/gems/sass-embedded-1.75.0-x86_64-linux/lib/sass/embedded.rb:37:in `compile_string'
        from /home/kali/gems/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:105:in `block in convert'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:84:in `render_document'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:211:in `render'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /home/kali/gems/gems/jekyll-4.3.3/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /home/kali/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /home/kali/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /home/kali/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /home/kali/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /home/kali/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /home/kali/gems/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
        from /home/kali/gems/bin/jekyll:25:in `load'
        from /home/kali/gems/bin/jekyll:25:in `<top (required)>'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
        from /home/kali/gems/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
        from /home/kali/gems/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /home/kali/gems/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
        from /usr/bin/bundle:25:in `load'
        from /usr/bin/bundle:25:in `<main>'
```

This issue was also mentioned [here](https://github.com/jekyll/jekyll/issues/9559)

### Steps To Reproduce

1. use the chirpy starter to generate a chirpy site
2. clone the repo locally and cd into it
3. run `bundle` to download the gems
4. run `bundle exec jekyll s`

### Expected Behavior

I would expect the site to be built and served locally

### Environment

- Ruby: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
- Jekyll: jekyll 4.3.3
- Chirpy: 6.5.5

### Anything else?

Thank you for this amazing theme!

**Comment by cotes2020** [comment]
You might consider reporting the issue to Jekyll repo.
