### ISSUE TITLE
can not parse map data in json

### ISSUE THREAD

**Issue by hxf0223** [cotes2020/jekyll-theme-chirpy#1747]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

I have a json in markdown file. 
```json
{
   "i": 287,
   "d": 3.14,
   "hello": "Hello World",
   "arr": [
      1,
      2,
      3
   ],
   "map": {
      "one": 1,
      "two": 2
   }
}
```

### Steps To Reproduce

There's an error when I post my blog up to github pages:
```sh
Configuration file: /home/runner/work/hxf0223.github.io/hxf0223.github.io/_config.yml
            Source: /home/runner/work/hxf0223.github.io/hxf0223.github.io
       Destination: /home/runner/work/hxf0223.github.io/hxf0223.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 21): Variable '{{"one", 1}' was not properly terminated with regexp: /\}\}/ in /home/runner/work/hxf0223.github.io/hxf0223.github.io/_posts/2023-05-5-good-cpp-repo-on-github.md
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:136:in `raise_missing_variable_terminator': Liquid syntax error (line 21): Variable '{{"one", 1}' was not properly terminated with regexp: /\}\}/ (Liquid::SyntaxError)
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:12[8](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:9):in `create_variable'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/block_body.rb:3[9](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:10):in `parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/document.rb:[10](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:11):in `parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/document.rb:5:in `parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/template.rb:130:in `parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/liquid-4.0.4/lib/liquid/template.rb:[11](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:12)4:in `parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/liquid_renderer/file.rb:[12](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:13):in `parse'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:124:in `render_liquid'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:80:in `render_document'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:557:in `block (2 levels) in render_docs'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:556:in `each'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:556:in `block in render_docs'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:555:in `each_value'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:555:in `render_docs'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:210:in `render'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/gems/jekyll-4.3.3/exe/jekyll:[15](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:16):in `<top (required)>'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `load'
	from /home/runner/work/hxf0223.github.io/hxf0223.github.io/vendor/bundle/ruby/3.2.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/3.2.0/bundler/friendly_errors.rb:1[17](https://github.com/hxf0223/hxf0223.github.io/actions/runs/9072223908/job/24927345949#step:5:18):in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.2.4/x64/bin/bundle:25:in `<main>'
Error: Process completed with exit code 1.
```

### Expected Behavior

Should there's no error in github Actions.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy:

**Comment by luckwyy** [comment]
I encountered the same problem

**Comment by NichtsHsu** [comment]
***You should ask questions in discussions, not issues.***

Jekyll uses liquid as its template syntax, which looks like:

```
{{ variable }}
{% if statement %}
```

Fragments with similar formats will be parsed as Liquid syntax.

[The jekyll documentation](https://jekyllrb.com/docs/liquid/tags/) describes how to avoid your fragments like this being recognized as liquid:

> If you are using a language that contains curly braces, you will likely need to place `{% raw %}` and `{% endraw %}` tags around your code. Since Jekyll `4.0`, you can add `render_with_liquid: false` in your front matter to disable Liquid entirely for a particular document.
