### ISSUE TITLE
Error: Custom property values may not be empty

### ISSUE THREAD

**Issue by CRCinAU** [cotes2020/jekyll-theme-chirpy#1806]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

When building with `JEKYLL_ENV=production`, the following error is encountered:

```
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    Error: Custom property values may not be empty. on line 5:26028 of ../../.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/dist/bootstrap.css from line 1:1 of ../../.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/main.bundle.scss from line 1:1 of jekyll-theme-chirpy.scss >> -bs-btn-close-color:#000;--bs-btn-close-bg:url("data:image/svg+xml,%3csvg xm ------------------------------------------^ 
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/share/gems/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: Custom property values may not be empty. (Jekyll::Converters::Scss::SyntaxError)
        on line 5:26028 of ../../.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/dist/bootstrap.css
        from line 1:1 of ../../.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/main.bundle.scss
        from line 1:1 of jekyll-theme-chirpy.scss
>> -bs-btn-close-color:#000;--bs-btn-close-bg:url("data:image/svg+xml,%3csvg xm
   ------------------------------------------^


        raise SyntaxError, e.to_s
              ^^^^^^^^^^^^^^^^^^^
        from /usr/share/gems/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:192:in `sass_convert'
        from /usr/share/gems/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:211:in `render'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/share/gems/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
        from /usr/bin/jekyll:25:in `load'
        from /usr/bin/jekyll:25:in `<top (required)>'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
        from /usr/share/gems/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/share/gems/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
        from /home/netwiz/bin/bundle:25:in `load'
        from /home/netwiz/bin/bundle:25:in `<main>'
/home/netwiz/.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/dist/bootstrap.css:5: Error: Custom property values may not be empty. (SassC::SyntaxError)
        on line 5:26028 of ../../.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/dist/bootstrap.css
        from line 1:1 of ../../.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1/_sass/main.bundle.scss
        from line 1:1 of jekyll-theme-chirpy.scss
>> -bs-btn-close-color:#000;--bs-btn-close-bg:url("data:image/svg+xml,%3csvg xm
   ------------------------------------------^

        from /usr/share/gems/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
        from /usr/share/gems/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:195:in `sass_convert'
        from /usr/share/gems/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:186:in `convert'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:105:in `block in convert'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `each'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `reduce'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:104:in `convert'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:84:in `render_document'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/renderer.rb:63:in `run'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:572:in `render_regenerated'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:564:in `block in render_pages'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `each'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:563:in `render_pages'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:211:in `render'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/site.rb:80:in `process'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:28:in `process_site'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:65:in `build'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:36:in `process'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `each'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /usr/share/gems/gems/jekyll-4.3.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /usr/share/gems/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /usr/share/gems/gems/jekyll-4.3.3/exe/jekyll:15:in `<top (required)>'
        from /usr/bin/jekyll:25:in `load'
        from /usr/bin/jekyll:25:in `<top (required)>'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:451:in `exec'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:34:in `dispatch'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/cli.rb:28:in `start'
        from /usr/share/gems/gems/bundler-2.5.9/exe/bundle:28:in `block in <top (required)>'
        from /usr/share/gems/gems/bundler-2.5.9/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/share/gems/gems/bundler-2.5.9/exe/bundle:20:in `<top (required)>'
        from /home/netwiz/bin/bundle:25:in `load'
        from /home/netwiz/bin/bundle:25:in `<main>'
```

This error does not occur if `JEKYLL_ENV` is not set.

### Steps To Reproduce

```bash
#!/bin/bash
export JEKYLL_ENV=production
bundle exec jekyll clean
bundle exec jekyll build
```

### Expected Behavior

Expect the site to build.

### Environment

- Ruby: ruby 3.3.1 (2024-04-23 revision c56cd86388) [x86_64-linux]

- Jekyll: jekyll 4.3.3

- Chirpy: 
```
  * jekyll-theme-chirpy (7.0.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /home/netwiz/.local/share/gem/ruby/gems/jekyll-theme-chirpy-7.0.1
```

**Comment by CRCinAU** [comment]
I don't know how, or why, but this error doesn't come up anymore. Closing as now I can no longer reproduce this issue.
