### ISSUE TITLE
Failing to start jekyll server

### ISSUE THREAD

**Issue by unbreakabl3** [cotes2020/jekyll-theme-chirpy#2094]
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Since 7.2.0 I am getting that error. On 7.1.1 it did work. Maybe someone have an idea what's wrong?

```
user@users:~/test > JEKYLL_ENV=production bundle exec jekyll serve --open-url --livereload --watch
logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
Configuration file: /test_config.yml
            Source: /test
       Destination: /test_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
1 │ @import 'dist/bootstrap';
  │         ^^^^^^^^^^^^^^^^
  ╵
    main.bundle.scss 1:9                                                                                   @use
    /testassets/css/jekyll-theme-chirpy.scss 1:1  root stylesheet
Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import

  ╷
2 │ @import 'main';
  │         ^^^^^^
  ╵
    main.bundle.scss 2:9                                                                                   @use
    /testassets/css/jekyll-theme-chirpy.scss 1:1  root stylesheet
Error: Can't find stylesheet to import.
  ╷
1 │ @import 'dist/bootstrap';
  │         ^^^^^^^^^^^^^^^^
  ╵
  main.bundle.scss 1:9                                                                                   @use
  /testassets/css/jekyll-theme-chirpy.scss 1:1  root stylesheet 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/jekyll-theme-chirpy.scss':
                    Can't find stylesheet to import.
                    ------------------------------------------------
      Jekyll 4.3.4   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/Users/user/.gem/ruby/3.3.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:175:in `rescue in convert': Can't find stylesheet to import. (Jekyll::Converters::Scss::SyntaxError)

        raise SyntaxError, e.message
              ^^^^^^^^^^^^^^^^^^^^^^
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:159:in `convert'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:105:in `block in convert'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:104:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:104:in `reduce'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:104:in `convert'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:84:in `render_document'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:63:in `run'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:572:in `render_regenerated'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:564:in `block in render_pages'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:563:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:563:in `render_pages'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:211:in `render'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:80:in `process'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:28:in `process_site'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:65:in `build'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:36:in `process'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/exe/jekyll:15:in `<top (required)>'
        from /Users/user/.gem/ruby/3.3.0/bin/jekyll:25:in `load'
        from /Users/user/.gem/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli.rb:455:in `exec'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli.rb:35:in `dispatch'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli.rb:29:in `start'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/exe/bundle:28:in `block in <top (required)>'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/exe/bundle:20:in `<top (required)>'
        from /etc/profiles/per-user/user/bin/bundle:25:in `load'
        from /etc/profiles/per-user/user/bin/bundle:25:in `<main>'
/Users/user/.gem/ruby/3.3.0/gems/sass-embedded-1.82.0-arm64-darwin/lib/sass/compiler/host.rb:86:in `compile_request': Can't find stylesheet to import. (Sass::CompileError)
        from /Users/user/.gem/ruby/3.3.0/gems/sass-embedded-1.82.0-arm64-darwin/lib/sass/compiler.rb:171:in `compile_string'
        from /Users/user/.gem/ruby/3.3.0/gems/sass-embedded-1.82.0-arm64-darwin/lib/sass/embedded.rb:37:in `compile_string'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-sass-converter-3.0.0/lib/jekyll/converters/scss.rb:160:in `convert'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:105:in `block in convert'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:104:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:104:in `reduce'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:104:in `convert'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:84:in `render_document'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/renderer.rb:63:in `run'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:572:in `render_regenerated'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:564:in `block in render_pages'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:563:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:563:in `render_pages'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:211:in `render'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/site.rb:80:in `process'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:28:in `process_site'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:65:in `build'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/build.rb:36:in `process'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /Users/user/.gem/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /Users/user/.gem/ruby/3.3.0/gems/jekyll-4.3.4/exe/jekyll:15:in `<top (required)>'
        from /Users/user/.gem/ruby/3.3.0/bin/jekyll:25:in `load'
        from /Users/user/.gem/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli.rb:455:in `exec'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli.rb:35:in `dispatch'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/cli.rb:29:in `start'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/exe/bundle:28:in `block in <top (required)>'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/user/.gem/ruby/3.3.0/gems/bundler-2.5.21/exe/bundle:20:in `<top (required)>'
        from /etc/profiles/per-user/user/bin/bundle:25:in `load'
        from /etc/profiles/per-user/user/bin/bundle:25:in `<main>'
```  

### Steps To Reproduce

Run `JEKYLL_ENV=production bundle exec jekyll serve --open-url --livereload --watch`

### Expected Behavior

Page should be generated and loaded.

### Environment

- Ruby: `ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [arm64-darwin24]`
- Jekyll:
```
logger was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add logger to your Gemfile or gemspec to silence this warning.
csv was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add csv to your Gemfile or gemspec to silence this warning.
/Users/user/.gem/ruby/3.3.0/gems/safe_yaml-1.0.5/lib/safe_yaml/load.rb:22: warning: base64 was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.4.0.
You can add base64 to your Gemfile or gemspec to silence this warning.
jekyll 4.3.4
```
- Chirpy:
```
* jekyll-theme-chirpy (7.2.1)
        Summary: A minimal, responsive, and feature-rich Jekyll theme for technical writing.
        Homepage: https://github.com/cotes2020/jekyll-theme-chirpy
        Documentation: https://github.com/cotes2020/jekyll-theme-chirpy/#readme
        Source Code: https://github.com/cotes2020/jekyll-theme-chirpy
        Wiki: https://github.com/cotes2020/jekyll-theme-chirpy/wiki
        Bug Tracker: https://github.com/cotes2020/jekyll-theme-chirpy/issues
        Path: /Users/leonidbelenkiy/.gem/ruby/3.3.0/gems/jekyll-theme-chirpy-7.2.1
```

**Comment by cotes2020** [comment]
It seems that you built the site from the source code and lost some project files during the upgrade process, and did not generate the assets yourself.

Please make sure you have read the contributor guide, which details when to report a bug. If you encounter difficulties in usage, you should post them in the community discussion.

**Comment by unbreakabl3** [comment]
> It seems that you built the site from the source code and lost some project files during the upgrade process, and did not generate the assets yourself.
> 
> Please make sure you have read the contributor guide, which details when to report a bug. If you encounter difficulties in usage, you should post them in the community discussion.

Hi there,

Thank you for your response. I’m curious to know why the issue is closed. I haven’t had a chance to provide any feedback yet.

I’m not building the project from the source code, but rather from the starter. Interestingly, the exact same project is working on 7.1.x and all previous versions, but it’s not working on 7.2.x. Does this mean that my project somehow converted from the starter to a source code-based project?

By the way, I used the published [upgrade guide](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide) to make the upgrade.
