### ISSUE TITLE
Missing parentheses

### ISSUE THREAD

**Issue by phls** [cotes2020/jekyll-theme-chirpy#3]
Hi,

I am trying to use your theme, but tere is a issue on the script.

$ ./run.sh 
Traceback (most recent call last):
  File "_scripts/tools/init_all.py", line 10, in <module>
    import update_posts_lastmod
  File "/srv/jekyll-theme-chirpy/.container/_scripts/tools/update_posts_lastmod.py", line 83
    print "[INFO] update 'lastmod' for:" + post
                                       ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[INFO] update 'lastmod' for:" + post)?

**Comment by phls** [comment]
If I add parentheses here: print ("[INFO] update 'lastmod' for:") + post

I got:

$ ./run.sh 
[INFO] Success to update lastmod for {} post(s).
Traceback (most recent call last):
  File "_scripts/tools/init_all.py", line 10, in <module>
    import update_posts_lastmod
  File "/srv/jekyll-theme-chirpy/.container/_scripts/tools/update_posts_lastmod.py", line 113, in <module>
    main()
  File "/srv/jekyll-theme-chirpy/.container/_scripts/tools/update_posts_lastmod.py", line 110, in main
    update_lastmod(verbose)
  File "/srv/jekyll-theme-chirpy/.container/_scripts/tools/update_posts_lastmod.py", line 85, in update_lastmod
    print ("[INFO] Success to update lastmod for {} post(s).").format(count)
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by imcloudfloating** [comment]
You are absolutely using python3.7, this script was python2.7, whitch means you have to use "print("something")".

**Comment by cotes2020** [comment]
Hi @phls,

As @imcloudfloating mentioned, the python tool scripts were developed in python27 and I'm considering upgrade them to python3.

**Comment by cotes2020** [comment]
Hi @phls,

The python scripts has been upgraded to python3 since d0b60f1e98427539c6c89e4cad447b5742336fb7.

If you still have trouble using it, please let me know in the comments.

**Comment by phls** [comment]
Hi @cotes2020  

Thanks! I will try.
