### ISSUE TITLE
Liquid Exception: undefined method `gsub' for 0:Integer in /home/runner/work/xeroslab.github.io/xeroslab.github.io/_layouts/post.html

### ISSUE THREAD

**Issue by XerosLab** [cotes2020/jekyll-theme-chirpy#415]
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

The following error occurs in the build site step of the github action.

```
Liquid Exception: undefined method `gsub' for 0:Integer in /home/runner/work/xeroslab.github.io/xeroslab.github.io/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

The overall error contents are as follows.

```
1m 6s
Run bundle exec jekyll b -d "_site$BASE_URL"
  bundle exec jekyll b -d "_site$BASE_URL"
  shell: /usr/bin/bash -e {0}
  env:
    JEKYLL_ENV: production
Configuration file: /home/runner/work/xeroslab.github.io/xeroslab.github.io/_config.yml
 Theme Config file: /home/runner/work/xeroslab.github.io/xeroslab.github.io/_config.yml
            Source: /home/runner/work/xeroslab.github.io/xeroslab.github.io
       Destination: /home/runner/work/xeroslab.github.io/xeroslab.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: undefined method `gsub' for 0:Integer in /home/runner/work/xeroslab.github.io/xeroslab.github.io/_layouts/post.html
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/utils.rb:364:in `replace_character_sequence_with_hyphen': undefined method `gsub' for 0:Integer (NoMethodError)
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/utils.rb:215:in `slugify'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/filters.rb:63:in `slugify'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:160:in `block (2 levels) in render_segment'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `each'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:158:in `block in render_segment'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:150:in `render_segment'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/for.rb:79:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:46:in `block (2 levels) in render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `each'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:44:in `block in render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/context.rb:123:in `stack'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/tags/if.rb:43:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/block_body.rb:82:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:131:in `render_liquid'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:194:in `render_layout'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:163:in `place_in_layouts'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:93:in `render_document'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/renderer.rb:63:in `run'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:547:in `render_regenerated'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:532:in `block (2 levels) in render_docs'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:531:in `each'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:531:in `block in render_docs'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:530:in `each_value'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:530:in `render_docs'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:210:in `render'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/site.rb:80:in `process'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
	from /home/runner/work/xeroslab.github.io/xeroslab.github.io/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/cli.rb:478:in `exec'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/exe/bundle:49:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/lib/ruby/gems/2.7.0/gems/bundler-2.2.28/exe/bundle:37:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/bin/bundle:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.7.4/x64/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.
```

I don't know why this problem suddenly occurred.

I used it for a month without any problems.

How can I solve this problem?

**Comment by NichtsHsu** [comment]
`0` is not a valid tag name at your post [2021-08-29-HTML_width_height_0](https://github.com/XerosLab/xeroslab.github.io/blob/main/_posts/2021-08-29-HTML_width_height_0.md), please use `'0'` instead.

**Comment by XerosLab** [comment]
> `0` is not a valid tag name at your post [2021-08-29-HTML_width_height_0](https://github.com/XerosLab/xeroslab.github.io/blob/main/_posts/2021-08-29-HTML_width_height_0.md), please use `'0'` instead.

Thank you so much, you made my day!!

Have a nice day

**Comment by XerosLab** [comment]
I handled it as you told me, but it still didn't work, so I deleted the post and it worked normally. Thank you.

**Comment by NichtsHsu** [comment]
> I handled it as you told me, but it still didn't work, so I deleted the post and it worked normally. Thank you.

**Not** rename the file name from `2021-08-29-HTML_width_height_0` to `2021-08-29-HTML_width_height`.

Modify the tag from:

```
---
title: HTML에서 img video 태그의 width나 height가 0이 되는 현상
date: 2021-08-29 23:40:00 +0900
categories: [Frontend, HTML]
tags: [HTML, width, height, 0]
---
```

to

```
---
title: HTML에서 img video 태그의 width나 height가 0이 되는 현상
date: 2021-08-29 23:40:00 +0900
categories: [Frontend, HTML]
tags: [HTML, width, height, '0']
---
```

**Comment by XerosLab** [comment]
omg I misunderstood. thank you so much
