### ISSUE TITLE
求助，执行init.sh时提示head: -: No such file or directory

### ISSUE THREAD

**Issue by handbye** [cotes2020/jekyll-theme-chirpy#73]
```bash
(base)  ~/Documents/写作目录/jekyll-theme-chirpy/ [master] sudo bash tools/init.sh
head: -: No such file or directory
head: -: No such file or directory
fatal: 有歧义的参数 '_posts/2019-03-30-segment'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/Routing.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2019-01-11-use-python'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/markdown-and-Pygments.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2018-07-16-ipsec'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/vpn.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2018-07-01-NAT'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/alg-ASPF.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2018-06-26-L2TP'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/VPN.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2018-06-19-mpls'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/vpn.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2018-06-08-SSL'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/VPN.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2018-03-15-web-login-esnp-USG6000V'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/2017-3-21-Komodo'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/Edit-python'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
fatal: 有歧义的参数 '_posts/IDE.md'：未知的版本或路径不存在于工作区中。
使用 '--' 来分隔版本和路径，例如：
'git <命令> [<版本>...] -- [<文件>...]'
Nothing changed.
```
然后文章的标签页和分类页全部提示404，访问时提示以下错误：

```bash
[2020-06-04 09:39:15] ERROR Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/filehandler.rb:333:in `set_filename'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/filehandler.rb:302:in `exec_handler'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/filehandler.rb:237:in `do_GET'
	/Users/admin/.gem/ruby/2.6.0/gems/jekyll-4.1.0/lib/jekyll/commands/serve/servlet.rb:160:in `do_GET'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/abstract.rb:105:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpservlet/filehandler.rb:233:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpserver.rb:140:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/httpserver.rb:96:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/webrick/server.rb:307:in `block in start_thread'
```

**Comment by handbye** [comment]
我检查了下文章的内容，文章中的categories写的格式不正确，我改过来了，现在_post目录下只留了一篇文章，执行init.sh时提示：
```bash
head: -: No such file or directory
head: -: No such file or directory
[master 9e30a19] [Automation] Updated the Lastmod for post(s).
 1 file changed, 3 deletions(-)
```

**Comment by handbye** [comment]
@cotes2020  你好，这个问题有办法解决吗？

**Comment by handbye** [comment]
> @cotes2020 你好，这个问题有办法解决吗？

这个问题解决了，可能是因为权限问题
