### ISSUE TITLE
tools/test.sh fails when there is only one level of Categories

### ISSUE THREAD

**Issue by bdolewski** [cotes2020/jekyll-theme-chirpy#79]
I just cloned the repository and decided to remove all data from `_posts`. Then I wrote a new article which also created new tags and new category.

My workflow is as follows
```
./tools/init.sh
./tools/build.sh
./tools/test.sh
```

My article has something like this in upper section:
```
title: My Title
date: 2020-06-07 11:32:00 +0200 
categories: [Tools]
tags: [fastlane, provisioning, certificates]
```

Now when I run `tools/test.sh` I get following error (everything was "green" before I removed demo articles and added mine.

```
Running ["ScriptCheck", "LinkCheck", "ImageCheck", "HtmlCheck"] on ["_site"] on *.html... 


Ran on 17 files!


- _site/tabs/categories/index.html
  *  linking to internal hash #l_Tools that does not exist (line 1)
     <a href="#l_Tools" data-toggle="collapse" aria-expanded="true" class="category-trigger hide-border-bottom"> <i class="fas fa-fw fa-angle-right disabled"></i> </a>
htmlproofer 3.15.3 | Error:  HTML-Proofer found 1 failure!
Traceback (most recent call last):
	25: from /usr/local/opt/ruby/bin/bundle:23:in `<main>'
	24: from /usr/local/opt/ruby/bin/bundle:23:in `load'
	23: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	22: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	21: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	20: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	10: from /usr/local/lib/ruby/gems/2.7.0/bin/htmlproofer:23:in `<top (required)>'
	 9: from /usr/local/lib/ruby/gems/2.7.0/bin/htmlproofer:23:in `load'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/html-proofer-3.15.3/bin/htmlproofer:11:in `<top (required)>'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/html-proofer-3.15.3/bin/htmlproofer:109:in `block (2 levels) in <top (required)>'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/html-proofer-3.15.3/lib/html-proofer/runner.rb:50:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/html-proofer-3.15.3/lib/html-proofer/runner.rb:174:in `print_failed_tests': \e[31mHTML-Proofer found 1 failure!\e[0m (RuntimeError)
```

**Comment by cotes2020** [comment]
Fixed, thanks for the report.
