### ISSUE TITLE
Github action failed with exit code 1

### ISSUE THREAD

**Issue by PinYuanChen** [cotes2020/jekyll-theme-chirpy#814]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug
Hello, I am a jekyll newbie and I used Chirpy starter as the template for my blog. A few days ago I could still build my blog without problem. But today I failed at setup Ruby step with following error message:
```
Error: Error: The process '/opt/hostedtoolcache/Ruby/3.2.0/x64/bin/bundle' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5371:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5354:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5248:27)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
### To Reproduce
You can see it [here](https://github.com/PinYuanChen/pinyuanchen.github.io/actions).

### Expected behavior
Run the github action without problem.

### Environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |         |
| `gem -v`                          |         |
| `bundle -v`                       |         |
| `bundle exec jekyll -v`           |         |
| `bundle info jekyll-theme-chirpy` |         |

**Comment by PinYuanChen** [comment]
I found it was the same issue with [this](https://github.com/cotes2020/jekyll-theme-chirpy/issues/811#issuecomment-1364902702). After I limited the ruby version to 3.1, everything went fine.
