### ISSUE TITLE
Broken Dependency nokogumbo

### ISSUE THREAD

**Issue by bcaddy** [cotes2020/jekyll-theme-chirpy#841]
## Checklist

- [x] I have read the [tutorials](https://cotes2020.github.io/chirpy-demo/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on [existing issues](https://github.com/cotes2020/jekyll-theme-chirpy/issues?q=is%3Aissue) (including closed ones).
- [x] I found the bug on the latest code of the `master` branch.

## Describe the bug

I can't build or deploy my site either locally or with GitHub Actions. I always get the following error when running `bundle install`. This used to work fine, you can even see and GHA build [here](https://github.com/bcaddy/bcaddy.github.io/actions/runs/3750650373/jobs/6572639444#step:4:246) that ran fine 2 weeks ago but when I reran it today it fails.
 
```
Installing nokogumbo 2.0.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20230106-72229-idujo0nokogumbo-2.0.5/gems/nokogumbo-2.0.5/ext/nokogumbo
/usr/local/opt/ruby/bin/ruby -I /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0 extconf.rb
checking for whether -I/usr/local/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-x86_64-darwin/ext/nokogiri is accepted as
CFLAGS... yes
checking for whether -I/usr/local/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-x86_64-darwin/ext/nokogiri/include is
accepted as CFLAGS... yes
checking for whether -I/usr/local/lib/ruby/gems/3.1.0/gems/nokogiri-1.13.10-x86_64-darwin/ext/nokogiri/include/libxml2 is
accepted as CFLAGS... yes
checking for libxml/tree.h... yes
checking for nokogiri.h... yes
creating Makefile

current directory: /tmp/bundler20230106-72229-idujo0nokogumbo-2.0.5/gems/nokogumbo-2.0.5/ext/nokogumbo
make DESTDIR\= sitearchdir\=./.gem.20230106-72229-r5m82o sitelibdir\=./.gem.20230106-72229-r5m82o clean

current directory: /tmp/bundler20230106-72229-idujo0nokogumbo-2.0.5/gems/nokogumbo-2.0.5/ext/nokogumbo
make DESTDIR\= sitearchdir\=./.gem.20230106-72229-r5m82o sitelibdir\=./.gem.20230106-72229-r5m82o
compiling nokogumbo.c
nokogumbo.c:492:27: warning: 'rb_cData' is deprecated: by: rb_cObject.  Will be removed in 3.1.
[-Wdeprecated-declarations]
  return Data_Wrap_Struct(rb_cData, parse_args_mark, RUBY_NEVER_FREE, args);
                          ^
/usr/local/Cellar/ruby/3.1.3/include/ruby-3.1.0/ruby/internal/core/rdata.h:394:18: note: expanded from macro 'rb_cData'
#define rb_cData rb_cData()
                 ^
/usr/local/Cellar/ruby/3.1.3/include/ruby-3.1.0/ruby/internal/core/rdata.h:372:1: note: 'rb_cData' has been explicitly
marked deprecated here
RBIMPL_ATTR_DEPRECATED(("by: rb_cObject.  Will be removed in 3.1."))
^
/usr/local/Cellar/ruby/3.1.3/include/ruby-3.1.0/ruby/internal/attr/deprecated.h:36:53: note: expanded from macro
'RBIMPL_ATTR_DEPRECATED'
# define RBIMPL_ATTR_DEPRECATED(msg) __attribute__((__deprecated__ msg))
                                                    ^
1 warning generated.
compiling ./../../gumbo-parser/src/ascii.c
compiling ./../../gumbo-parser/src/attribute.c
compiling ./../../gumbo-parser/src/char_ref.c
compiling ./../../gumbo-parser/src/error.c
./../../gumbo-parser/src/error.c:99:20: warning: cast to smaller integer type 'GumboTag' from 'void *'
[-Wvoid-pointer-to-enum-cast]
    GumboTag tag = (GumboTag) error->tag_stack.data[i];
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
compiling ./../../gumbo-parser/src/foreign_attrs.c
compiling ./../../gumbo-parser/src/parser.c
./../../gumbo-parser/src/parser.c:540:10: warning: cast to smaller integer type 'GumboInsertionMode' from 'void *'
[-Wvoid-pointer-to-enum-cast]
  return (GumboInsertionMode) modes->data[(modes->length - 1)];
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
compiling ./../../gumbo-parser/src/string_buffer.c
compiling ./../../gumbo-parser/src/string_piece.c
compiling ./../../gumbo-parser/src/svg_attrs.c
compiling ./../../gumbo-parser/src/svg_tags.c
compiling ./../../gumbo-parser/src/tag.c
compiling ./../../gumbo-parser/src/tag_lookup.c
compiling ./../../gumbo-parser/src/token_buffer.c
compiling ./../../gumbo-parser/src/tokenizer.c
compiling ./../../gumbo-parser/src/utf8.c
compiling ./../../gumbo-parser/src/util.c
compiling ./../../gumbo-parser/src/vector.c
linking shared-object nokogumbo/nokogumbo.bundle
Undefined symbols for architecture x86_64:
  "_Nokogiri_wrap_xml_document", referenced from:
      _parse_continue in nokogumbo.o
  "_cNokogiriXmlSyntaxError", referenced from:
      _add_errors in nokogumbo.o
  "_htmlNewDocNoDtD", referenced from:
      _parse_continue in nokogumbo.o
  "_mNokogiri", referenced from:
      _Init_nokogumbo in nokogumbo.o
  "_xmlAddChild", referenced from:
      _build_tree in nokogumbo.o
  "_xmlCreateIntSubset", referenced from:
      _parse_continue in nokogumbo.o
  "_xmlFreeDoc", referenced from:
      _parse_cleanup in nokogumbo.o
  "_xmlNewCDataBlock", referenced from:
      _build_tree in nokogumbo.o
  "_xmlNewDocComment", referenced from:
      _build_tree in nokogumbo.o
  "_xmlNewDocNode", referenced from:
      _build_tree in nokogumbo.o
  "_xmlNewDocText", referenced from:
      _build_tree in nokogumbo.o
  "_xmlNewNs", referenced from:
      _build_tree in nokogumbo.o
  "_xmlNewNsProp", referenced from:
      _build_tree in nokogumbo.o
  "_xmlSearchNs", referenced from:
      _build_tree in nokogumbo.o
  "_xmlSetNs", referenced from:
      _build_tree in nokogumbo.o
ld: symbol(s) not found for architecture x86_64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [nokogumbo.bundle] Error 1

make failed, exit code 2

Gem files will remain installed in /tmp/bundler20230106-72229-idujo0nokogumbo-2.0.5/gems/nokogumbo-2.0.5 for inspection.
Results logged to
/tmp/bundler20230106-72229-idujo0nokogumbo-2.0.5/extensions/x86_64-darwin-22/3.1.0/nokogumbo-2.0.5/gem_make.out

  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:102:in `run'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:51:in `block in make'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:43:in `each'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:43:in `make'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:171:in `build_extension'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in build_extensions'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/ext/builder.rb:202:in `build_extensions'
  /usr/local/Cellar/ruby/3.1.3/lib/ruby/3.1.0/rubygems/installer.rb:843:in `build_extensions'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/source/rubygems.rb:207:in `install'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/installer/parallel_installer.rb:177:in `block in
worker_pool'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.24/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing nokogumbo (2.0.5), and Bundler cannot continue.

In Gemfile:
  html-proofer was resolved to 3.19.2, which depends on
    nokogumbo
```

### To Reproduce

1. Run `bundle install`

### Expected behavior

Bundle install shouldn't fail

### Environment

This is my local environment, not the GHA environment

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |    ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-darwin22]     |
| `gem -v`                          |      3.3.26   |
| `bundle -v`                       |   Bundler version 2.3.24      |
| `bundle exec jekyll -v`           |     Could not find nokogumbo-2.0.5 in locally installed gems
Run `bundle install` to install missing gems.    |
| `bundle info jekyll-theme-chirpy` |    Could not find nokogumbo-2.0.5 in locally installed gems     |

**Comment by cotes2020** [comment]
Jekyll's dependency `nokogiri` does not yet support Ruby 3.2, so just update your website to Chirpy 5.4.0, as it locks the latest version of Ruby to v3.1.x in gemspec (same goes for gh-actions workflow). See also: 09e4ad245b5f1101eacbc55b89e8e8dee05df746.

**Comment by bcaddy** [comment]
After fighting with my Ruby install for a bit that did it. Thank you
